// Generated by CoffeeScript 1.12.4
(function() {
  var Settings, bson, db, mongojs;

  Settings = require("settings-sharelatex");

  mongojs = require("mongojs");

  bson = require("bson");

  db = mongojs(Settings.mongo.url, ["docHistory", "projectHistoryMetaData", "docHistoryIndex"]);

  module.exports = {
    db: db,
    ObjectId: mongojs.ObjectId,
    BSON: new bson.BSONPure()
  };

}).call(this);

//# sourceMappingURL=mongojs.js.map
