// Generated by CoffeeScript 1.12.4
(function() {
  var DiffManager, DocumentUpdaterManager, RestoreManager, logger;

  DocumentUpdaterManager = require("./DocumentUpdaterManager");

  DiffManager = require("./DiffManager");

  logger = require("logger-sharelatex");

  module.exports = RestoreManager = {
    restoreToBeforeVersion: function(project_id, doc_id, version, user_id, callback) {
      if (callback == null) {
        callback = function(error) {};
      }
      logger.log({
        project_id: project_id,
        doc_id: doc_id,
        version: version,
        user_id: user_id
      }, "restoring document");
      return DiffManager.getDocumentBeforeVersion(project_id, doc_id, version, function(error, content) {
        if (error != null) {
          return callback(error);
        }
        return DocumentUpdaterManager.setDocument(project_id, doc_id, content, user_id, function(error) {
          if (error != null) {
            return callback(error);
          }
          return callback();
        });
      });
    }
  };

}).call(this);

//# sourceMappingURL=RestoreManager.js.map
